- name: Setup Docker
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Update
      apt:
        update_cache: true
        upgrade: dist
        force_apt_get: true
    - name: Install Docker
      apt:
        pkg:
          - docker.io
          - docker-compose
        update_cache: true
        state: latest
